const TermsAndConditions = () => {
    return (
      <div className="max-w-4xl mx-auto px-6 py-12 text-gray-800 leading-relaxed">
        <h1 className="text-3xl font-bold mb-6">📄 Terms & Conditions</h1>
  
        <p className="mb-4">
          This document is an electronic record in terms of the Information Technology Act, 2000,
          and rules thereunder as applicable, including amended provisions relating to electronic
          records. This electronic record is generated by a computer system and does not require
          any physical or digital signatures.
        </p>
  
        <p className="mb-4">
          This document is published in accordance with Rule 3 (1) of the Information Technology
          (Intermediaries Guidelines) Rules, 2011, requiring publication of rules, regulations,
          privacy policy, and Terms of Use for access or usage of
          https://www.dreamtorank.com/ (“Website”), including related mobile sites and applications
          (collectively referred to as the “Platform”).
        </p>
  
        <p className="mb-4">
          The Platform is owned by <strong>S.N TRADERS (Owner: Shivam Srivastav)</strong>,
          incorporated under the Companies Act, 1956, with its registered office in Etawah, U.P
          (referred to as “Platform Owner”, “we”, “us”, or “our”).
        </p>
  
        <p className="mb-6">
          By accessing, browsing, or using the Platform, you agree to be bound by these Terms
          of Use and all applicable policies incorporated herein by reference.
        </p>
  
        <h2 className="text-xl font-semibold mb-4 uppercase">
          Accessing, Browsing, or Otherwise Using the Platform Indicates Your Agreement
        </h2>
  
        <div className="space-y-6">
  
          <section>
            <h3 className="font-semibold mb-2">1. Accuracy of Information</h3>
            <p>
              You agree to provide true, accurate, and complete information during and after
              registration and are responsible for all activities under your account.
            </p>
          </section>
  
          <section>
            <h3 className="font-semibold mb-2">2. No Warranty</h3>
            <p>
              We do not provide any warranty regarding accuracy, performance, or suitability
              of information or Services. We exclude liability to the fullest extent permitted by law.
            </p>
          </section>
  
          <section>
            <h3 className="font-semibold mb-2">3. At Your Own Risk</h3>
            <p>
              Your use of the Platform and Services is entirely at your own risk. You are
              responsible for assessing whether the Services meet your requirements.
            </p>
          </section>
  
          <section>
            <h3 className="font-semibold mb-2">4. Intellectual Property</h3>
            <p>
              All content, including design, layout, graphics, and materials, is proprietary
              to us or licensed to us. You may not claim any intellectual property rights in the content.
            </p>
          </section>
  
          <section>
            <h3 className="font-semibold mb-2">5. Unauthorized Use</h3>
            <p>
              Unauthorized use of the Platform may result in legal action under applicable laws.
            </p>
          </section>
  
          <section>
            <h3 className="font-semibold mb-2">6. Service Charges</h3>
            <p>
              You agree to pay all charges associated with availing the Services.
            </p>
          </section>
  
          <section>
            <h3 className="font-semibold mb-2">7. Lawful Use</h3>
            <p>
              You agree not to use the Platform for unlawful or prohibited purposes under Indian law.
            </p>
          </section>
  
          <section>
            <h3 className="font-semibold mb-2">8. Third-Party Links</h3>
            <p>
              The Platform may contain links to third-party websites. Upon accessing such links,
              you will be governed by their respective policies and terms.
            </p>
          </section>
  
          <section>
            <h3 className="font-semibold mb-2">9. Legally Binding Contract</h3>
            <p>
              Initiating a transaction constitutes a legally binding contract between you and
              the Platform Owner.
            </p>
          </section>
  
          <section>
            <h3 className="font-semibold mb-2">10. Indemnity</h3>
            <p>
              You agree to indemnify and hold harmless the Platform Owner and its affiliates
              from any claims, damages, or expenses arising from your breach of these Terms
              or violation of applicable laws.
            </p>
          </section>
  
          <section>
            <h3 className="font-semibold mb-2">11. Limitation of Liability</h3>
            <p>
              The Platform Owner shall not be liable for indirect or consequential damages.
              Liability shall not exceed the amount paid by you for the Service or Rs. 100,
              whichever is lower.
            </p>
          </section>
  
          <section>
            <h3 className="font-semibold mb-2">12. Force Majeure</h3>
            <p>
              Neither party shall be liable for failure to perform obligations due to force
              majeure events beyond reasonable control.
            </p>
          </section>
  
          <section>
            <h3 className="font-semibold mb-2">13. Governing Law & Jurisdiction</h3>
            <p>
              These Terms shall be governed by the laws of India. All disputes shall be subject
              to the exclusive jurisdiction of the courts in Uttar Pradesh.
            </p>
          </section>
  
          <section>
            <h3 className="font-semibold mb-2">14. Contact Information</h3>
            <p>
              All concerns or communications relating to these Terms must be communicated using
              the contact information provided on this website.
            </p>
          </section>
  
        </div>
      </div>
    );
  };
  
  export default TermsAndConditions;
  